// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4ERUGoCZrq_GS4ZIhUoSBN26X29kNwQ',
    appId: '1:717725493715:web:abb8ad0d54761a705fa726',
    messagingSenderId: '717725493715',
    projectId: 'ticket-app-odk',
    authDomain: 'ticket-app-odk.firebaseapp.com',
    storageBucket: 'ticket-app-odk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvt-1sk-qFHBvVwodUxv98srQzrU4uRFM',
    appId: '1:717725493715:android:61b447bb680a51495fa726',
    messagingSenderId: '717725493715',
    projectId: 'ticket-app-odk',
    storageBucket: 'ticket-app-odk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBWeUZrw1tfJ5_cp_4gW01zqYm1w8BuM',
    appId: '1:717725493715:ios:565fa9f6ee2eaeaa5fa726',
    messagingSenderId: '717725493715',
    projectId: 'ticket-app-odk',
    storageBucket: 'ticket-app-odk.appspot.com',
    iosBundleId: 'com.example.ticketAppOdk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBWeUZrw1tfJ5_cp_4gW01zqYm1w8BuM',
    appId: '1:717725493715:ios:565fa9f6ee2eaeaa5fa726',
    messagingSenderId: '717725493715',
    projectId: 'ticket-app-odk',
    storageBucket: 'ticket-app-odk.appspot.com',
    iosBundleId: 'com.example.ticketAppOdk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP4ERUGoCZrq_GS4ZIhUoSBN26X29kNwQ',
    appId: '1:717725493715:web:a7b5f8591e8a13f65fa726',
    messagingSenderId: '717725493715',
    projectId: 'ticket-app-odk',
    authDomain: 'ticket-app-odk.firebaseapp.com',
    storageBucket: 'ticket-app-odk.appspot.com',
  );
}
